#:schema https://github.com/joshmedeski/sesh/raw/main/sesh.schema.json

[[session]]
name = "Downloads 📥"
path = "~/Downloads"
startup_command = "ll -sdate"

[[session]]
name = "tmux config"
path = "~/.config/tmux"
startup_command = "nvim tmux.conf"
preview_command = "bat --color=always ~/.config/tmux/tmux.conf"
windows = [ "git" ]

[[window]]
name = "git"
startup_script = "lazygit"

[[session]]
name = "1-plain"
path = "/opt/plain/support-app"
windows = [ "services" ]

[[session]]
name = "2-plain"
path = "/opt/plain/support-app2"
windows = [ "services2" ]

[[session]]
name = "3-plain"
path = "/opt/plain/support-app3"
windows = [ "services4" ]

[[session]]
name = "sales-dashboard plain"
# path = "~/.config/tmux"
# startup_command = "nvim tmux.conf"
# preview_command = "bat --color=always ~/.config/tmux/tmux.conf"
windows = [ "sales-dashboard" ]

[[session]]
name = "scratch"
# path = "~/.config/tmux"
# startup_command = "nvim tmux.conf"
# preview_command = "bat --color=always ~/.config/tmux/tmux.conf"
# windows = [ "" ]

[[window]]
name = "supportapp"
path  = "/opt/plain/support-app"

[[window]]
name = "supportapp2"
path  = "/opt/plain/support-app2"

[[window]]
name = "services"
path  = "/opt/plain/services"

[[window]]
name = "services2"
path  = "/opt/plain/services2"

[[window]]
name = "services4"
path  = "/opt/plain/services4"

[[window]]
name = "supportapp3"
path  = "/opt/plain/support-app3"

[[window]]
name = "sales-dashboard"
path  = "/opt/plain/sales-dashboard"
