version: '3'
services:
 radarr:
  container_name: radarr2
  restart: unless-stopped
  ports:
   - 7878:7878
  volumes:
    - /opt/radarr/config:/config
    - /mnt/wasabi/movies:/movies
    - /opt/downloads/movies:/downloads
  links:
    - "jackett:jackett"
  environment:
   - PUID=420
   - PGID=420
   - TZ=Europe/Berlin
  image: lscr.io/linuxserver/radarr:latest
 
 sonarr:
  container_name: sonarr
  restart: unless-stopped
  ports:
   - 8989:8989
  links:
    - "jackett:jackett"
  volumes:
    - /opt/sonarr/config:/config
    - /mnt/wasabi/tv:/tv
    - /opt/downloads/tv:/downloads
  environment:
   - PUID=420
   - PGID=420
   - TZ=Europe/Berlin
  image: lscr.io/linuxserver/sonarr:latest
 
 jackett:
  container_name: jackett
  restart: unless-stopped
  ports:
   - 9117:9117
  volumes:
   - /opt/jackett:/config
  environment:
   - PUID=420
   - PGID=420
   - TZ=Europe/Berlin
  image: linuxserver/jackett
