name: scp files to server
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: copy file via ssh key
      uses: appleboy/scp-action@latest
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        source: ".dotfiles/setup/bootstrap.sh"
        target: "/var/www/html/init"
        overwrite: true
