name: shellchecker
on:
  - push
jobs:
  sh-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run the sh-checker
        uses: luizm/action-sh-checker@v0.1.12
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          SHFMT_OPTS: -i 2
        with:
          sh_checker_comment: true
          sh_checker_shellcheck_disable: true
          sh_checker_exclude: ".config/i3/dmenu-emoji.sh"
